version: "3"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5173:5173

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3001:3001
    depends_on:
      - database
    environment:
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: db
    networks:
      - app-network
  
  database:
    image: mysql:latest
    container_name: db
    restart: always 
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - ./.docker/data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
