version: "3"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5173:5173

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3001:3001
    depends_on:
      - db
    networks:
      - app-network
  
  db:
    platform: linux/x86_64
    image: postgres:13
    hostname: db
    container_name: database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

networks:
  app-network:
    driver: bridge
